// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Net_Core_Common_Model.Entity;

#nullable disable

namespace Net_Core_Common_Model.Migrations
{
    [DbContext(typeof(CEntityContext))]
    [Migration("20221229091938_20221229_2")]
    partial class _20221229_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Net_Core_Common_Model.Entity.Sys.CTab_SysCodeDetail", b =>
                {
                    b.Property<string>("Cfk_CodeMain_Code")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Cfk_CodeMain_Code")
                        .HasComment("類別代號");

                    b.Property<string>("Ck_CodeDet_Code")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ck_CodeDet_Code")
                        .HasComment("代碼代號");

                    b.Property<string>("CodeDet_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CodeDet_Name")
                        .HasComment("代碼名稱");

                    b.Property<string>("CodeDet_Remark")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CodeDet_Remark")
                        .HasComment("備註");

                    b.Property<string>("CodeDet_State")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("CodeDet_State")
                        .HasComment("狀態：「0:停用，1:啟用」");

                    b.HasKey("Cfk_CodeMain_Code");

                    b.ToTable("Sy_Code_Detail");

                    b.HasComment("系統代碼檔(代碼明細)");
                });

            modelBuilder.Entity("Net_Core_Common_Model.Entity.Sys.CTab_SysCodeMain", b =>
                {
                    b.Property<string>("Pk_CodeMain_Code")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Pk_CodeMain_Code")
                        .HasComment("類別代號");

                    b.Property<DateTime>("CodeMain_CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CodeMain_CreateDate")
                        .HasComment("建檔日期");

                    b.Property<string>("CodeMain_CreateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CodeMain_CreateId")
                        .HasComment("建立者ID");

                    b.Property<string>("CodeMain_CreateIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("CodeMain_CreateIp")
                        .HasComment("建立者IP");

                    b.Property<DateTime>("CodeMain_EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CodeMain_EditDate")
                        .HasComment("異動日期");

                    b.Property<string>("CodeMain_EditId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CodeMain_EditId")
                        .HasComment("異動者ID");

                    b.Property<string>("CodeMain_EditIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("CodeMain_EditIp")
                        .HasComment("異動者IP");

                    b.Property<string>("CodeMain_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CodeMain_Name")
                        .HasComment("類別名稱");

                    b.Property<string>("CodeMain_Remark")
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("CodeMain_Remark")
                        .HasComment("備註");

                    b.Property<string>("CodeMain_State")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("CodeMain_State")
                        .HasComment("狀態：「0:停用，1:啟用」");

                    b.HasKey("Pk_CodeMain_Code");

                    b.ToTable("Sys_Code_Main");

                    b.HasComment("系統代碼檔(代碼類別)");
                });

            modelBuilder.Entity("Net_Core_Common_Model.Entity.Sys.CTab_SysLogError", b =>
                {
                    b.Property<long>("Pk_LogError")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Pk_LogError")
                        .HasComment("主鍵");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Pk_LogError"), 1L, 1);

                    b.Property<string>("LogError_Agent")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LogError_Agent")
                        .HasComment("UserAgent");

                    b.Property<DateTime>("LogError_CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("LogError_CreateDate")
                        .HasComment("建檔日期");

                    b.Property<string>("LogError_CreateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LogError_CreateId")
                        .HasComment("建立者ID(Log的建立者有可能是訪客，所以型態用String)");

                    b.Property<string>("LogError_CreateIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("LogError_CreateIp")
                        .HasComment("建立者IP");

                    b.Property<string>("LogError_ExceptionMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LogError_ExceptionMessage")
                        .HasComment("Exception Message");

                    b.Property<string>("LogError_ExceptionSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LogError_ExceptionSource")
                        .HasComment("Exception Source");

                    b.Property<string>("LogError_ExceptionStackTrace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LogError_ExceptionStackTrace")
                        .HasComment("Exception StackTrace");

                    b.Property<string>("LogError_ExceptionTargetSite")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LogError_ExceptionTargetSite")
                        .HasComment("Exception TargetSite");

                    b.Property<string>("LogError_ExceptionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LogError_ExceptionType")
                        .HasComment("Exception Type");

                    b.Property<string>("LogError_IisHost")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LogError_IisHost")
                        .HasComment("IIS HOST");

                    b.HasKey("Pk_LogError");

                    b.ToTable("Sys_Log_Error");

                    b.HasComment("錯誤Log");
                });

            modelBuilder.Entity("Net_Core_Common_Model.Entity.Sys.CTab_SysLogExecute", b =>
                {
                    b.Property<long>("Pk_LogExec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Pk_LogExec")
                        .HasComment("主鍵");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Pk_LogExec"), 1L, 1);

                    b.Property<string>("LogExec_Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LogExec_Action")
                        .HasComment("執行動作");

                    b.Property<string>("LogExec_ChangeItem")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LogExec_ChangeItem")
                        .HasComment("異動項目");

                    b.Property<DateTime>("LogExec_CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("LogExec_CreateDate")
                        .HasComment("異動時間");

                    b.Property<string>("LogExec_CreateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LogExec_CreateCode")
                        .HasComment("異動者ID");

                    b.Property<string>("LogExec_CreateIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("LogExec_CreateIp")
                        .HasComment("異動者IP");

                    b.Property<string>("LogExec_Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LogExec_Module")
                        .HasComment("異動作業");

                    b.HasKey("Pk_LogExec");

                    b.ToTable("Sys_Log_Execute");

                    b.HasComment("系統操作歷程");
                });

            modelBuilder.Entity("Net_Core_Common_Model.Entity.Sys.CTab_SysLogLogin", b =>
                {
                    b.Property<long>("Pk_LogLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Pk_LogLogin")
                        .HasComment("主鍵");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Pk_LogLogin"), 1L, 1);

                    b.Property<string>("LogLogin_Account")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LogLogin_Account")
                        .HasComment("帳號");

                    b.Property<DateTime>("LogLogin_CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("LogLogin_CreateDate")
                        .HasComment("建檔日期");

                    b.Property<string>("LogLogin_CreateIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("LogLogin_CreateIp")
                        .HasComment("建立者IP");

                    b.Property<string>("LogLogin_IisHost")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LogLogin_IisHost")
                        .HasComment("IIS HOST");

                    b.Property<string>("LogLogin_Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("LogLogin_Message")
                        .HasComment("登入訊息");

                    b.Property<bool>("LogLogin_Result")
                        .HasColumnType("bit")
                        .HasColumnName("LogLogin_Result")
                        .HasComment("登入成功與否 (0:失敗，1成功)");

                    b.Property<string>("LogLogin_UserAgent")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LogLogin_UserAgent")
                        .HasComment("UserAgent");

                    b.HasKey("Pk_LogLogin");

                    b.ToTable("Sys_Log_Login");

                    b.HasComment("登入Log");
                });

            modelBuilder.Entity("Net_Core_Common_Model.Entity.Sys.CTab_SysLogTrajectory", b =>
                {
                    b.Property<long>("Pk_LogTra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Pk_LogTra")
                        .HasComment("主鍵");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Pk_LogTra"), 1L, 1);

                    b.Property<string>("LogTra_Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LogTra_Action")
                        .HasComment("Route Action");

                    b.Property<string>("LogTra_Agent")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LogTra_Agent")
                        .HasComment("UserAgent");

                    b.Property<string>("LogTra_Controller")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LogTra_Controller")
                        .HasComment("Route Controller");

                    b.Property<DateTime>("LogTra_CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("LogTra_CreateDate")
                        .HasComment("建檔日期");

                    b.Property<string>("LogTra_CreateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LogTra_CreateId")
                        .HasComment("建立者ID(Log的建立者有可能是訪客，所以型態用String)");

                    b.Property<string>("LogTra_CreateIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("LogTra_CreateIp")
                        .HasComment("建立者IP");

                    b.Property<string>("LogTra_Group")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LogTra_Group")
                        .HasComment("Route Group");

                    b.Property<string>("LogTra_IisHost")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LogTra_IisHost")
                        .HasComment("IIS HOST");

                    b.Property<string>("LogTra_RequestContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LogTra_RequestContent")
                        .HasComment("Request內容");

                    b.Property<DateTime>("LogTra_RequestTime")
                        .HasColumnType("datetime")
                        .HasColumnName("LogTra_RequestTime")
                        .HasComment("Request時間");

                    b.Property<string>("LogTra_ResponseContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LogTra_ResponseContent")
                        .HasComment("Response內容");

                    b.Property<DateTime>("LogTra_ResponseTime")
                        .HasColumnType("datetime")
                        .HasColumnName("LogTra_ResponseTime")
                        .HasComment("Response時間");

                    b.HasKey("Pk_LogTra");

                    b.ToTable("Sys_Log_Trajectory");

                    b.HasComment("程式執行Log");
                });

            modelBuilder.Entity("Net_Core_Common_Model.Entity.Sys.CTab_SysModule", b =>
                {
                    b.Property<long>("Pk_Module")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Pk_Mod")
                        .HasComment("主鍵");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Pk_Module"), 1L, 1);

                    b.Property<long>("FK_ModuleClass")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_ModuleClass")
                        .HasComment("選單分類主鍵");

                    b.Property<DateTime>("Module_CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Module_CreateDate")
                        .HasComment("建檔日期");

                    b.Property<string>("Module_CreateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Module_CreateId")
                        .HasComment("建立者ID");

                    b.Property<string>("Module_CreateIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Module_CreateIp")
                        .HasComment("建立者IP");

                    b.Property<string>("Module_Discern")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Module_Discern")
                        .HasComment("作業識別碼");

                    b.Property<DateTime>("Module_EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Module_EditDate")
                        .HasComment("異動日期");

                    b.Property<string>("Module_EditId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Module_EditId")
                        .HasComment("異動者ID");

                    b.Property<string>("Module_EditIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Module_EditIp")
                        .HasComment("異動者IP");

                    b.Property<DateTime>("Module_EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Module_EndDate")
                        .HasComment("有效日期迄");

                    b.Property<string>("Module_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Module_Name")
                        .HasComment("作業名稱");

                    b.Property<decimal>("Modulethis._order")
                        .HasColumnType("decimal(9,0)")
                        .HasColumnName("Modulethis._order")
                        .HasComment("排序(升冪)");

                    b.Property<string>("Modulethis._outLink")
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Modulethis._outLink")
                        .HasComment("作業外部連結：點擊系統左側選單時，會直接跳轉外部連結");

                    b.Property<string>("Module_Route")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Module_Route")
                        .HasComment("作業路徑");

                    b.Property<DateTime>("Module_StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Module_StartDate")
                        .HasComment("有效日期起");

                    b.Property<string>("Module_State")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Module_State")
                        .HasComment("狀態：「0:停用，1:啟用」");

                    b.HasKey("Pk_Module");

                    b.ToTable("Sys_Module");

                    b.HasComment("選單作業");
                });

            modelBuilder.Entity("Net_Core_Common_Model.Entity.Sys.CTab_SysModuleClass", b =>
                {
                    b.Property<long>("Pk_ModuleClass")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Pk_ModuleClass")
                        .HasComment("主鍵");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Pk_ModuleClass"), 1L, 1);

                    b.Property<DateTime>("ModClass_CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("ModClass_CreateDate")
                        .HasComment("建檔日期");

                    b.Property<string>("ModClass_CreateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ModClass_CreateId")
                        .HasComment("建立者ID");

                    b.Property<string>("ModClass_CreateIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ModClass_CreateIp")
                        .HasComment("建立者IP");

                    b.Property<DateTime>("ModClass_EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("ModClass_EditDate")
                        .HasComment("異動日期");

                    b.Property<string>("ModClass_EditId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ModClass_EditId")
                        .HasComment("異動者ID");

                    b.Property<string>("ModClass_EditIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ModClass_EditIp")
                        .HasComment("異動者IP");

                    b.Property<string>("ModClass_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ModClass_Name")
                        .HasComment("分類名稱");

                    b.Property<decimal>("ModClassthis._order")
                        .HasColumnType("decimal(9,0)")
                        .HasColumnName("ModClassthis._order")
                        .HasComment("排序(升冪)");

                    b.Property<long?>("ModClass_Parent")
                        .HasColumnType("bigint")
                        .HasColumnName("ModClass_Parent")
                        .HasComment("上層分類(選單分類的主鍵)");

                    b.Property<string>("ModClass_State")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("ModClass_State")
                        .HasComment("狀態：「0:停用，1:啟用」");

                    b.HasKey("Pk_ModuleClass");

                    b.ToTable("Sys_Module_Class");

                    b.HasComment("選單分類");
                });

            modelBuilder.Entity("Net_Core_Common_Model.Entity.Sys.CTab_SysModuleControl", b =>
                {
                    b.Property<long>("Cfk_Module")
                        .HasColumnType("bigint")
                        .HasColumnName("Cfk_Module")
                        .HasComment("選單作業主鍵");

                    b.Property<string>("ModCon_Code")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ModCon_Code")
                        .HasComment("選單作業控制項-識別碼");

                    b.Property<string>("ModCon_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ModCon_Name")
                        .HasComment("選單作業控制項-名稱");

                    b.HasKey("Cfk_Module", "ModCon_Code");

                    b.ToTable("Sys_Module_Control");

                    b.HasComment("選單作業控制項");
                });

            modelBuilder.Entity("Net_Core_Common_Model.Entity.Sys.CTab_SysParameter", b =>
                {
                    b.Property<string>("Ck_Par_Group")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ck_Par_Group")
                        .HasComment("參數群組");

                    b.Property<string>("Ck_Par_Code")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ck_Par_Code")
                        .HasComment("參數編號");

                    b.Property<DateTime>("Par_CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Par_CreateDate")
                        .HasComment("建檔日期");

                    b.Property<string>("Par_CreateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Par_CreateId")
                        .HasComment("建立者ID");

                    b.Property<string>("Par_CreateIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Par_CreateIp")
                        .HasComment("建立者IP");

                    b.Property<DateTime>("Par_EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Par_EditDate")
                        .HasComment("異動日期");

                    b.Property<string>("Par_EditId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Par_EditId")
                        .HasComment("異動者ID");

                    b.Property<string>("Par_EditIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Par_EditIp")
                        .HasComment("異動者IP");

                    b.Property<string>("Par_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Par_Name")
                        .HasComment("參數名稱");

                    b.Property<string>("Par_Remarks")
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Par_Remarks")
                        .HasComment("說明");

                    b.Property<string>("Par_State")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Par_State")
                        .HasComment("狀態：「0:停用，1:啟用」");

                    b.Property<string>("Par_Value1")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Par_Value1")
                        .HasComment("值1");

                    b.Property<string>("Par_Value10")
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Par_Value10")
                        .HasComment("值10");

                    b.Property<string>("Par_Value2")
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Par_Value2")
                        .HasComment("值2");

                    b.Property<string>("Par_Value3")
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Par_Value3")
                        .HasComment("值3");

                    b.Property<string>("Par_Value4")
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Par_Value4")
                        .HasComment("值4");

                    b.Property<string>("Par_Value5")
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Par_Value5")
                        .HasComment("值5");

                    b.Property<string>("Par_Value6")
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Par_Value6")
                        .HasComment("值6");

                    b.Property<string>("Par_Value7")
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Par_Value7")
                        .HasComment("值7");

                    b.Property<string>("Par_Value8")
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Par_Value8")
                        .HasComment("值8");

                    b.Property<string>("Par_Value9")
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Par_Value9")
                        .HasComment("值9");

                    b.HasKey("Ck_Par_Group", "Ck_Par_Code");

                    b.ToTable("Sys_Parameter");

                    b.HasComment("系統參數檔");
                });

            modelBuilder.Entity("Net_Core_Common_Model.Entity.User.CTab_UserInfo", b =>
                {
                    b.Property<long>("Pk_Info")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Pk_Info")
                        .HasComment("主鍵");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Pk_Info"), 1L, 1);

                    b.Property<string>("Info_Account")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Info_Account")
                        .HasComment("登入帳號");

                    b.Property<string>("Info_AccountAd")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Info_AccountAd")
                        .HasComment("AD帳號");

                    b.Property<DateTime>("Info_CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Info_CreateDate")
                        .HasComment("建檔日期");

                    b.Property<string>("Info_CreateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Info_CreateId")
                        .HasComment("建立者ID");

                    b.Property<string>("Info_CreateIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Info_CreateIp")
                        .HasComment("建立者IP");

                    b.Property<string>("Info_Disable")
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Info_Disable")
                        .HasComment("停用原因-選項");

                    b.Property<string>("Info_DisableReason")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Info_DisableReason")
                        .HasComment("停用原因：[選項：其他]的值");

                    b.Property<DateTime>("Info_EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Info_EditDate")
                        .HasComment("異動日期");

                    b.Property<string>("Info_EditId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Info_EditId")
                        .HasComment("異動者ID");

                    b.Property<string>("Info_EditIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Info_EditIp")
                        .HasComment("異動者IP");

                    b.Property<string>("Info_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Info_Email")
                        .HasComment("信箱");

                    b.Property<DateTime>("Info_EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Info_EndDate")
                        .HasComment("有效日期迄");

                    b.Property<decimal>("Info_ErrorCount")
                        .HasColumnType("decimal(3,0)")
                        .HasColumnName("Info_ErrorCount")
                        .HasComment("登入錯誤次數");

                    b.Property<string>("Info_IsAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Info_IsAd")
                        .HasComment("帳號類別：「0:獨立，1:AD」");

                    b.Property<bool?>("Info_IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("Info_IsAdmin")
                        .HasComment("系統管理者");

                    b.Property<bool?>("Info_Lock")
                        .HasColumnType("bit")
                        .HasColumnName("Info_Lock")
                        .HasComment("帳號鎖定");

                    b.Property<DateTime?>("Info_LockDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Info_LockDate")
                        .HasComment("帳號鎖定時間");

                    b.Property<string>("Info_LockIp")
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Info_LockIp")
                        .HasComment("帳號鎖定IP");

                    b.Property<string>("Info_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Info_Name")
                        .HasComment("姓名");

                    b.Property<string>("Info_Password")
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Info_Password")
                        .HasComment("密碼");

                    b.Property<DateTime>("Info_StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Info_StartDate")
                        .HasComment("有效日期起");

                    b.Property<string>("Info_State")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Info_State")
                        .HasComment("狀態：「0:停用，1:啟用」");

                    b.Property<DateTime?>("Info_UpdatePwDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Info_UpdatePwDate")
                        .HasComment("更換密碼日期");

                    b.HasKey("Pk_Info");

                    b.ToTable("User_Info");

                    b.HasComment("使用者資訊");
                });

            modelBuilder.Entity("Net_Core_Common_Model.Entity.User.CTab_UserInfoAuth", b =>
                {
                    b.Property<long>("Cfk_Info")
                        .HasColumnType("bigint")
                        .HasColumnName("Cfk_Info")
                        .HasComment("使用者主鍵");

                    b.Property<long>("Cfk_Module")
                        .HasColumnType("bigint")
                        .HasColumnName("Cfk_Module")
                        .HasComment("選單作業主鍵");

                    b.HasKey("Cfk_Info", "Cfk_Module");

                    b.ToTable("User_Info_Auth");

                    b.HasComment("使用者作業權限");
                });

            modelBuilder.Entity("Net_Core_Common_Model.Entity.User.CTab_UserInfoControl", b =>
                {
                    b.Property<long>("Cfk_Info")
                        .HasColumnType("bigint")
                        .HasColumnName("Cfk_Info")
                        .HasComment("使用者主鍵");

                    b.Property<long>("Cfk_Module")
                        .HasColumnType("bigint")
                        .HasColumnName("Cfk_Module")
                        .HasComment("選單作業主鍵");

                    b.Property<string>("Cfk_ModCon_Code")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Cfk_ModuleControl")
                        .HasComment("選單作業控制項");

                    b.HasKey("Cfk_Info", "Cfk_Module", "Cfk_ModCon_Code");

                    b.ToTable("User_Info_Control");
                });

            modelBuilder.Entity("Net_Core_Common_Model.Entity.User.CTab_UserInfoPassword", b =>
                {
                    b.Property<long>("Cfk_Info")
                        .HasColumnType("bigint")
                        .HasColumnName("Cfk_Info")
                        .HasComment("使用者主鍵");

                    b.Property<long>("Ck_InfoPas_Sn")
                        .HasColumnType("bigint")
                        .HasColumnName("Ck_InfoPas_Sn")
                        .HasComment("流水號：記錄變更的序號");

                    b.Property<DateTime>("InfoPas_CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("InfoPas_CreateDate")
                        .HasComment("建檔日期");

                    b.Property<string>("InfoPas_CreateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("InfoPas_CreateId")
                        .HasComment("建立者ID");

                    b.Property<string>("InfoPas_CreateIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("InfoPas_CreateIp")
                        .HasComment("建立者IP");

                    b.Property<string>("InfoPas_Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("InfoPas_Password")
                        .HasComment("新密碼");

                    b.HasKey("Cfk_Info", "Ck_InfoPas_Sn");

                    b.ToTable("User_Info_Password");

                    b.HasComment("使用者密碼變更記錄");
                });

            modelBuilder.Entity("Net_Core_Common_Model.Entity.User.CTab_UserRole", b =>
                {
                    b.Property<long>("Pk_Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Pk_Role")
                        .HasComment("主鍵");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Pk_Role"), 1L, 1);

                    b.Property<DateTime>("Role_CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Role_CreateDate")
                        .HasComment("建檔日期");

                    b.Property<string>("Role_CreateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Role_CreateId")
                        .HasComment("建立者ID");

                    b.Property<string>("Role_CreateIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Role_CreateIp")
                        .HasComment("建立者IP");

                    b.Property<DateTime>("Role_EditDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Role_EditDate")
                        .HasComment("異動日期");

                    b.Property<string>("Role_EditId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Role_EditId")
                        .HasComment("異動者ID");

                    b.Property<string>("Role_EditIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Role_EditIp")
                        .HasComment("異動者IP");

                    b.Property<DateTime>("Role_EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Role_EndDate")
                        .HasComment("有效日期迄");

                    b.Property<string>("Role_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Role_Name")
                        .HasComment("角色名稱");

                    b.Property<DateTime>("Role_StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Role_StartDate")
                        .HasComment("有效日期起");

                    b.Property<string>("Role_State")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Role_State")
                        .HasComment("狀態：「0:停用，1:啟用」");

                    b.HasKey("Pk_Role");

                    b.ToTable("User_Role");

                    b.HasComment("使用者角色設定");
                });

            modelBuilder.Entity("Net_Core_Common_Model.Entity.User.CTab_UserRoleAuth", b =>
                {
                    b.Property<long>("Cfk_Role")
                        .HasColumnType("bigint")
                        .HasColumnName("Cfk_Role")
                        .HasComment("使用者角色主鍵");

                    b.Property<long>("Cfk_Module")
                        .HasColumnType("bigint")
                        .HasColumnName("Cfk_Module")
                        .HasComment("選單作業主鍵");

                    b.HasKey("Cfk_Role", "Cfk_Module");

                    b.ToTable("User_Role_Auth");

                    b.HasComment("使用者角色作業權限");
                });

            modelBuilder.Entity("Net_Core_Common_Model.Entity.User.CTab_UserRoleControl", b =>
                {
                    b.Property<long>("Cfk_Role")
                        .HasColumnType("bigint")
                        .HasColumnName("Cfk_Role")
                        .HasComment("角色主鍵");

                    b.Property<long>("Cfk_Module")
                        .HasColumnType("bigint")
                        .HasColumnName("Cfk_Module")
                        .HasComment("選單作業主鍵");

                    b.Property<string>("Cfk_ModCon_Code")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Cfk_ModuleControl")
                        .HasComment("選單作業控制項");

                    b.HasKey("Cfk_Role", "Cfk_Module", "Cfk_ModCon_Code");

                    b.ToTable("User_Role_Control");

                    b.HasComment("使用者角色作業控制項權限");
                });

            modelBuilder.Entity("Net_Core_Common_Model.Entity.User.CTab_UserRoleMember", b =>
                {
                    b.Property<long>("Cfk_Role")
                        .HasColumnType("bigint")
                        .HasColumnName("Cfk_Role")
                        .HasComment("使用者角色主鍵");

                    b.Property<long>("Cfk_Info")
                        .HasColumnType("bigint")
                        .HasColumnName("Cfk_Info")
                        .HasComment("使用者主鍵");

                    b.HasKey("Cfk_Role", "Cfk_Info");

                    b.ToTable("User_Role_Member");

                    b.HasComment("使用者角色成員");
                });
#pragma warning restore 612, 618
        }
    }
}
